---
# Task to list all mapped configurations
- name: List configurations
  shell: infrasim config list
  become: true
  register: out
  tags: configlist
- debug: var={{ item }}
  with_items: out.stdout_lines
  tags: configlist


# Task to change node type for specified node
- lineinfile:
    dest: "{{ ansible_env.HOME }}/.infrasim/.node_map/{{ node_name }}.yml"
    regexp: '^(type:(\s)).*'
    line: '\1{{ node_type }}'
    backrefs: true
    state: present
  become: false
  register: out
  tags: changetype
- debug: var={{ item }}
  with_items: out
  tags: changetype


# Task to remove node config
- name: Delete node config
  shell: infrasim config delete {{ node_name }}
  become: true
  register: out
  tags: delconfig
- debug: var={{ item }}
  with_items: out.stdout_lines
  tags: delconfig


# Tasks to transfer yml file to hosts and add to config
- copy: 
    src: "{{ yml_path }}"
    dest: "{{ ansible_env.HOME }}/tmp.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  become: false
  tags: addconfig
  register: out
- debug: var={{ item }}
  with_items: out
  tags: addconfig
- name: Add node config 
  shell: infrasim config add {{ node_name }} {{ ansible_env.HOME }}/tmp.yml
  become: true
  tags: addconfig
  register: out
- debug: var={{ item }}
  with_items: out.stdout_lines
  tags: addconfig

# Tasks to transfer yml file to hosts and update node config
- copy: 
    src: "{{ yml_path }}"
    dest: "{{ ansible_env.HOME }}/tmp.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  become: false
  tags: updateconfig
  register: out
- debug: var={{ item }}
  with_items: out
  tags: updateconfig

- name: Update node config
  shell: infrasim config update {{ node_name }} {{ ansible_env.HOME }}/tmp.yml
  become: true
  register: out
  tags: updateconfig
- debug: var={{ item }}
  with_items: out.stdout_lines
  tags: updateconfig

